## Broadcasting

In [1]:
import numpy as np

In [5]:
x=np.array([[1,2,3]])
print(x.shape)
y=np.array([[4],[5]])
print(y.shape)

(1, 3)
(2, 1)


In [12]:
x,y=np.broadcast_arrays(x,y)

In [7]:
x

array([[1, 2, 3],
       [1, 2, 3]])

In [8]:
y

array([[4, 4, 4],
       [5, 5, 5]])

In [10]:
np.shape(x)

(2, 3)

In [11]:
np.shape(y)

(2, 3)

In [6]:
x+y

array([[5, 6, 7],
       [6, 7, 8]])

In [7]:
x.shape

(2, 3)

In [8]:
y.shape

(2, 3)