In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
a*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [2]:
print a

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(a)? (<ipython-input-2-da1608c9d425>, line 1)

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [5]:
numpyArray=np.array([22,5,2,7,7],dtype="float16")

In [6]:
numpyArray

array([22.,  5.,  2.,  7.,  7.], dtype=float16)

In [7]:
type(numpyArray)

numpy.ndarray

In [8]:
numpyArray=np.array([22.4,3,65.4,5],dtype="int8")
numpyArray

array([22,  3, 65,  5], dtype=int8)

In [9]:
type(numpyArray)

numpy.ndarray

In [11]:
numpyArray=np.array([1,2,3,4],dtype=np.int32)
numpyArray

array([1, 2, 3, 4])

In [13]:
type(numpyArray)

numpy.ndarray

In [14]:
randomArray=np.random.randint(10)

In [16]:
randomArray=np.random.randn(10)
randomArray

array([-1.89512696e+00,  9.37560482e-01,  8.97419902e-01, -4.84809076e-01,
       -1.92761989e-01, -9.47892203e-01, -2.33271875e-01, -1.82114008e-03,
       -1.78517047e+00, -1.04739411e+00])

In [17]:
randomarray.ndim

NameError: name 'randomarray' is not defined

In [18]:
randomArray.ndim

1

In [19]:
randomArray.shape

(10,)

In [20]:
twoD=np.array([[1,2,3],[4,5,6],[7,8,9]])
type(twoD)

numpy.ndarray

In [21]:
twoD

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
shape(twoD)

NameError: name 'shape' is not defined

In [23]:
twoD.shape

(3, 3)

In [24]:
twoD.ndim

2

In [25]:
zeroD=np.array(100)
zeroD.ndim

0

In [26]:
oneD=np.array([1])
oneD.ndim

1

In [27]:
twoD=np.array([[99]])
print(twoD)
print(twoD.ndim)

[[99]]
2


In [51]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
b=np.arange(12)
b
b.reshape(3,4)
a=b.reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
flat=np.ravel(a)
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [120]:
a=np.arange(1,31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [121]:
a.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [125]:
flat=np.ravel(a)
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [126]:
b=np.arange(36)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [136]:
flat=np.ravel(a)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [128]:
flat=np.ravel(b)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [129]:
b.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [130]:
b.reshape(36)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [131]:
b.reshape(3,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [137]:
twoD=np.arange(36).reshape(6,6)
twoD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [138]:
threeD=twoD.reshape(4,3,3)
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

###  Square root

### Mirror operation on matrix

In [142]:
m1=np.arange(12).reshape(4,3)
m2=np.random.randn(12).reshape(4,3)
bm1+m2          #shape should e same for mirror operation

array([[-0.91227155, -0.15312064,  0.30894294],
       [ 4.03970602,  3.63377836,  3.40582226],
       [ 6.09295513,  7.94969406,  7.87409077],
       [11.13230153,  9.35872875, 10.91827897]])

In [143]:
n1=np.array([[1,2],[3,4]])
n2=np.array([[5,6],[7,8]])
n1+n2

array([[ 6,  8],
       [10, 12]])

# Indexing and slicing

In [28]:
twoD[0]

array([99])

In [29]:
twoD[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [30]:
twoD[0]

array([99])

In [32]:
oneD=np.array([1,2,3,4,5,6])
oneD[-1]

6

In [33]:
oneD[4]

5

In [34]:
oneD[-3]

4

In [35]:
oneD[2:4]

array([3, 4])

In [37]:
twoD=np.array([[1,2,3],[4,5,6],[7,8,9]])
#twoD[1]  if we give 1 index then it will consider whole row and will retrieve it
twoD[2][1]

8

In [38]:
twoD[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
twoD

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
#left side for rows and right side for columns
twoD[0:2,1:]

array([[2, 3],
       [5, 6]])

In [41]:
twoD[0:2,0:1]

array([[1],
       [4]])

In [43]:
threeD=np.array([[[100,200,300],[400,500,600],[700,800,900]]])
print(threeD.ndim)
print(threeD.shape)

3
(1, 3, 3)


In [44]:
threeD

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [45]:
threeD[0]

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

In [46]:
threeD[0][2]  #first we have to read 2D and in 2D there is only one dimension so write 0 and then move to inner array

array([700, 800, 900])

In [47]:
threeD[0,1]

array([400, 500, 600])

In [57]:
threeD[0][1][1]

500

In [58]:
arr3D=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[100,200,300],[400,500,600],[700,800,900]]])
arr3D

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [59]:
arr3D[1,2,2]

900

In [60]:
arr3D[1,1,1]

500

In [61]:
arr3D[0][:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr3D[0,:2,1:]

array([[2, 3],
       [5, 6]])

# Practice

In [69]:
arr2D=np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,3],[7,5,1,6,5],[8,2,4,9,7]])
arr2D

array([[ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5],
       [ 4,  0,  6,  2,  5],
       [ 6,  6,  1,  5,  3],
       [ 7,  5,  1,  6,  5],
       [ 8,  2,  4,  9,  7]])

In [71]:
arr2D[2:4,1:4]

array([[0, 6, 2],
       [6, 1, 5]])

In [75]:
arr=np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [78]:
arr[2:4,2:5]

array([[15, 16, 17],
       [21, 22, 23]])

In [79]:
arr[2]

array([13, 14, 15, 16, 17, 18])

In [80]:
arr[4]

array([25, 26, 27, 28, 29, 30])

In [81]:
arr[2:3,:]

array([[13, 14, 15, 16, 17, 18]])

In [82]:
arr[2:3]

array([[13, 14, 15, 16, 17, 18]])

In [83]:
arr[2]

array([13, 14, 15, 16, 17, 18])

In [86]:
arr[:,2]   #in row we can't left empty before row

array([ 3,  9, 15, 21, 27, 33])

In [87]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [88]:
arr[1:5,]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [89]:
arr[1:5]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [90]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [91]:
arr[2:4,5:]   #it will give us matrix(2 dimensional)

array([[18],
       [24]])

In [92]:
arr[2:4,5]   #it will give us vector(1 dimensional)

array([18, 24])

In [93]:
arr[2:4,-1]

array([18, 24])

In [94]:
arr[2:4,-1:]

array([[18],
       [24]])

In [95]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [96]:
arr[:,::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [97]:
arr[:,::-2]

array([[ 6,  4,  2],
       [12, 10,  8],
       [18, 16, 14],
       [24, 22, 20],
       [30, 28, 26],
       [36, 34, 32]])

In [98]:
arr[:,::3]

array([[ 1,  4],
       [ 7, 10],
       [13, 16],
       [19, 22],
       [25, 28],
       [31, 34]])

In [99]:
arr[::2,:]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18],
       [25, 26, 27, 28, 29, 30]])

In [100]:
arr[::-2,:]

array([[31, 32, 33, 34, 35, 36],
       [19, 20, 21, 22, 23, 24],
       [ 7,  8,  9, 10, 11, 12]])

In [101]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [102]:
arr[::2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [103]:
arr[2:5:2,::2]

array([[13, 15, 17],
       [25, 27, 29]])

In [104]:
arr[1::2,::2]

array([[ 7,  9, 11],
       [19, 21, 23],
       [31, 33, 35]])

## Boolean indexing

In [152]:
names=np.array(['Joe','Bol','Will','Bol','Will','Joe','Bol'])
names

array(['Joe', 'Bol', 'Will', 'Bol', 'Will', 'Joe', 'Bol'], dtype='<U4')

In [153]:
data=np.random.randn(7,4)

In [154]:
names == "Saad"

array([False, False, False, False, False, False, False])

In [155]:
names == "Bob"

array([False, False, False, False, False, False, False])

In [156]:
names!="Bob"

array([ True,  True,  True,  True,  True,  True,  True])

In [157]:
data

array([[-0.86277958,  0.49502381, -0.16811306, -0.70100272],
       [-0.91904828, -0.70952917, -1.18390572, -0.80701741],
       [ 1.32452752,  0.51048724, -0.45045215,  1.76178577],
       [-1.13523409,  0.38516086,  1.69458142, -0.98866974],
       [-0.55505116,  0.57576223, -1.49316289, -0.85842547],
       [ 1.46698174, -0.90795846, -0.60309456,  0.19952664],
       [-1.08331286,  0.05300824,  0.1710667 , -2.07584278]])

In [158]:
data>1

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False,  True],
       [False, False,  True, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [159]:
data[data>1]   #if we require exact values then put it in frame of data again

array([1.32452752, 1.76178577, 1.69458142, 1.46698174])

In [114]:
print(names=="Bob")
print(data)
print(data[names=="Bob"])  #it will return 2 rows because bob is present on 0th and 3rd row

[ True False False  True False False False]
[[ 0.39292496  0.88826319  0.49503449  1.08344255]
 [-0.60193639 -0.06906644 -0.21928531  0.41686446]
 [ 1.31867842 -1.25307968  0.09626385  0.81102688]
 [ 1.18448824 -0.95419929  0.33727174 -0.27319177]
 [ 1.42960161  0.85721882 -0.99362214 -2.64177306]
 [-0.80723397  0.37523988 -0.4923039  -0.40429674]
 [ 1.86641119  0.61891574 -2.07579305 -0.26820062]]
[[ 0.39292496  0.88826319  0.49503449  1.08344255]
 [ 1.18448824 -0.95419929  0.33727174 -0.27319177]]


In [160]:
data[True,False,False,False,False,True,False]   #it will give answer in object form so give array in boolean form

array([], shape=(0, 7, 4), dtype=float64)

In [161]:
bol = np.array([True,False,False,False,False,True,False],dtype="bool")
data[bol]    #it will return 0th and 5th row of data array

array([[-0.86277958,  0.49502381, -0.16811306, -0.70100272],
       [ 1.46698174, -0.90795846, -0.60309456,  0.19952664]])

In [162]:
names != "Joe"

array([False,  True,  True,  True,  True, False,  True])

In [147]:
data[names!="Joe"]

array([[ 0.39292496,  0.88826319,  0.49503449,  1.08344255],
       [ 1.31867842, -1.25307968,  0.09626385,  0.81102688],
       [ 1.18448824, -0.95419929,  0.33727174, -0.27319177],
       [ 1.42960161,  0.85721882, -0.99362214, -2.64177306]])

In [163]:
condition = names!="Joe"
condition

array([False,  True,  True,  True,  True, False,  True])

In [164]:
data[condition]

array([[-0.91904828, -0.70952917, -1.18390572, -0.80701741],
       [ 1.32452752,  0.51048724, -0.45045215,  1.76178577],
       [-1.13523409,  0.38516086,  1.69458142, -0.98866974],
       [-0.55505116,  0.57576223, -1.49316289, -0.85842547],
       [-1.08331286,  0.05300824,  0.1710667 , -2.07584278]])

In [165]:
data[~condition]

array([[-0.86277958,  0.49502381, -0.16811306, -0.70100272],
       [ 1.46698174, -0.90795846, -0.60309456,  0.19952664]])

In [166]:
data[condition,1:3]

array([[-0.70952917, -1.18390572],
       [ 0.51048724, -0.45045215],
       [ 0.38516086,  1.69458142],
       [ 0.57576223, -1.49316289],
       [ 0.05300824,  0.1710667 ]])

In [169]:
data1=np.arange(28).reshape(7,4)
print(data1)
print(condition)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True  True  True False  True]


In [170]:
data1[condition,1:3]

array([[ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [25, 26]])

In [171]:
data1[~condition,1:3]

array([[ 1,  2],
       [21, 22]])

In [172]:
names

array(['Joe', 'Bol', 'Will', 'Bol', 'Will', 'Joe', 'Bol'], dtype='<U4')

In [173]:
name1 = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
name1

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [178]:
condition1=(names=="Bob")&(names=="Joe")

In [180]:
condition1  # it will give all false because joe and bob will never appear together in array

array([False, False, False, False, False, False, False])

In [182]:
condition2 = (name1=="Bob")|(name1=="Joe")
condition2

array([ True,  True, False,  True, False,  True,  True])

# Fancy indexing

In [184]:
arr = np.empty((8,4))
for i in range(8):
    arr[i]=i

In [185]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [187]:
arr[[1,4,1]]

array([[1., 1., 1., 1.],
       [4., 4., 4., 4.],
       [1., 1., 1., 1.]])

In [188]:
arr[[1,4,2,6]]

array([[1., 1., 1., 1.],
       [4., 4., 4., 4.],
       [2., 2., 2., 2.],
       [6., 6., 6., 6.]])

In [191]:
arr[[4,0,1,6],[2,3,0,1]]  #it will make ordered pair
#(4,2),(0,3),(1,0),(6,1)

array([4., 0., 1., 6.])

In [193]:
arr1=np.arange(32).reshape(8,4)
print(arr1)
arr1[[1,5,7,2]][:,[0,3,1,2]]
#(1,0)(1,3)(1,1)(1,2)(5,0)(5,3)(5,1)(5,2)(7,0)()()()()....

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [195]:
arr1=np.arange(32).reshape(8,4)
print(arr1)
arr1[[1,5,7,2]][[0,3,1,2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

# Transpose of a matrix

In [199]:
t=arr1.T
t

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [200]:
t.transpose()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [201]:
z=[1,45,2,6,45,3,2,3,1,45]
st = set(z)
print(z)
st

[1, 45, 2, 6, 45, 3, 2, 3, 1, 45]


{1, 2, 3, 6, 45}

In [202]:
#defining a set
ast = {11,22,3,1,3,22,3}
ast

{1, 3, 11, 22}

# Conatenating  arrays

In [203]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [204]:
arr2 = np.array([[7,8,9],[10,11,12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [206]:
np.concatenate([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [208]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [209]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# Stack

In [210]:
np.stack([arr1,arr2])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [211]:
np.vstack([arr1,arr2])    #in vertical stack rows will increase

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [213]:
np.hstack([arr1,arr2])    #in horizontal stack columns will increase       

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [215]:
arrr=np.arange(36).reshape(6,6)
arrr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [216]:
np.vsplit(arrr,3)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [217]:
np.hsplit(arrr,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [218]:
arrr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])