## Broadcasting

In [1]:
import numpy as np

In [2]:
x=np.array([[1,2,3]])
print(x.shape)
y=np.array([[4],[5]])
print(y.shape)

(1, 3)
(2, 1)


In [3]:
x,y=np.broadcast_arrays(x,y)

In [4]:
x

array([[1, 2, 3],
       [1, 2, 3]])

In [5]:
y

array([[4, 4, 4],
       [5, 5, 5]])

In [6]:
x+y

array([[5, 6, 7],
       [6, 7, 8]])

In [7]:
x.shape

(2, 3)

In [8]:
y.shape

(2, 3)

# Pandas

In [17]:
import pandas as pd

In [ ]:
Pandas data structures(Series and data frame)

In [19]:
s1=pd.Series([11,22,33,44,55,66,77,88,99,10])  #pandas series object

In [20]:
s1

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
9    10
dtype: int64

In [21]:
# 0-9 are default index given by series object
s1[9]  #accessing by index

10

In [22]:
s1[1,4,2]   #wrong

KeyError: (1, 4, 2)

In [23]:
s1[[1,4,2,7]]   #accessing multiple values

1    22
4    55
2    33
7    88
dtype: int64

In [24]:
s1[5]=555         #modifying a value in series
s1[[1,4,2]]=[111,444,222]      #multiple values modification

In [25]:
s1

0     11
1    111
2    222
3     44
4    444
5    555
6     77
7     88
8     99
9     10
dtype: int64

In [26]:
del s1[5]  #deleting a value in series

In [27]:
s1

0     11
1    111
2    222
3     44
4    444
6     77
7     88
8     99
9     10
dtype: int64

In [30]:
del s1[0]

In [31]:
s1

1    111
2    222
3     44
4    444
6     77
7     88
8     99
9     10
dtype: int64

In [34]:
s1[12]=65   #insertion in a series with a new index

In [33]:
s1

1     111
2     222
3      44
4     444
6      77
7      88
8      99
9      10
12     65
dtype: int64

# Defining our own indexes(other than default)

In [37]:
s2=pd.Series([10,20,30,40],index=["oranges","apples","bananas","mangoes"])  #index name cannot modify

In [38]:
s2

oranges    10
apples     20
bananas    30
mangoes    40
dtype: int64

In [39]:
s2.index

Index(['oranges', 'apples', 'bananas', 'mangoes'], dtype='object')

In [40]:
s2.values

array([10, 20, 30, 40], dtype=int64)

In [43]:
ourIndex=["oranges","apples","bananas","mangoes"]    #index and values are separtely defined
s3=pd.Series([23,456,74,67],index=ourIndex)
s3

oranges     23
apples     456
bananas     74
mangoes     67
dtype: int64

In [44]:
s3>70

oranges    False
apples      True
bananas     True
mangoes    False
dtype: bool

In [45]:
s1[s1<30]

9    10
dtype: int64

In [46]:
s2[s2<30]

oranges    10
apples     20
dtype: int64

In [47]:
s2<30

oranges     True
apples      True
bananas    False
mangoes    False
dtype: bool

In [49]:
'peach' in s2    #hecking if required key is available in a series

False

In [51]:
'apples' in s3

True

# Creating a series by using a dictionary 

In [53]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
data = pd.Series(sdata)
data

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [54]:
states=['California','Ohio','Oregon','Texas']
data1= pd.Series(sdata,index=states)

In [61]:
data1

California     4000.0
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [59]:
data1.isnull()

California    False
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [57]:
data1['California']=4000
data1

California     4000.0
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [58]:
data1.isnull()

California    False
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [64]:
data1.notnull()

California    True
Ohio          True
Oregon        True
Texas         True
dtype: bool

# Dataframes

In [70]:
data = {
    'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
    'year':[2000,2001,2002,2001,2002,2003],
    'pop':[1.2,1.7,3.6,2.4,2.9,3.2]
    }
df1 = pd.DataFrame(data)
df1

state  year  pop
0    Ohio  2000  1.2
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [66]:
mydata = {
    'name':['Kulsoom','Hamdah','Muniba'],
    'year':['1st','4th','3rd'],
    'gpa':[3.8,3.9,4],
    'marks':[200,213,127]
}
df2 = pd.DataFrame(mydata)
df2

name year  gpa  marks
0  Kulsoom  1st  3.8    200
1   Hamdah  4th  3.9    213
2   Muniba  3rd  4.0    127

In [67]:
type(df1)

pandas.core.frame.DataFrame

In [68]:
type(df2)

pandas.core.frame.DataFrame

In [71]:
df1.shape

(6, 3)

In [72]:
df1['pop']     #selecting single column by column header

0    1.2
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

In [75]:
df1[['pop','state']]         #seleting multiple columns by column headers

pop   state
0  1.2    Ohio
1  1.7    Ohio
2  3.6    Ohio
3  2.4  Nevada
4  2.9  Nevada
5  3.2  Nevada

In [76]:
del df1['pop']     #deleting a column from dataframe
df1

state  year
0    Ohio  2000
1    Ohio  2001
2    Ohio  2002
3  Nevada  2001
4  Nevada  2002
5  Nevada  2003

In [77]:
df1['debt']=1000
df1

state  year  debt
0    Ohio  2000  1000
1    Ohio  2001  1000
2    Ohio  2002  1000
3  Nevada  2001  1000
4  Nevada  2002  1000
5  Nevada  2003  1000

In [81]:
df1['debt']=1000
df1

state  year  debt
0    Ohio  2000  1000
1    Ohio  2001  1000
2    Ohio  2002  1000
3  Nevada  2001  1000
4  Nevada  2002  1000
5  Nevada  2003  1000

In [82]:
df1['debt']=[1000,2000,3000,4000,5000,6000]
df1

state  year  debt
0    Ohio  2000  1000
1    Ohio  2001  2000
2    Ohio  2002  3000
3  Nevada  2001  4000
4  Nevada  2002  5000
5  Nevada  2003  6000

In [85]:
df1['debt']=range(6)
df1

state  year  debt
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4
5  Nevada  2003     5

In [86]:
df1['debt']=df1['state']       #we can pick values from column of same data frame or some other data frame
df1

state  year    debt
0    Ohio  2000    Ohio
1    Ohio  2001    Ohio
2    Ohio  2002    Ohio
3  Nevada  2001  Nevada
4  Nevada  2002  Nevada
5  Nevada  2003  Nevada

In [87]:
df2

name year  gpa  marks
0  Kulsoom  1st  3.8    200
1   Hamdah  4th  3.9    213
2   Muniba  3rd  4.0    127

In [107]:
dic = {
    "AI for everyone":[67,89,26,90,78,76],
    "Python1":[89,67,37,96,56,78],
    "Python2":[92,87,68,79,24,46]}
df3 = pd.DataFrame(dic,index=["A","B","C","D","E","F"])
df3

AI for everyone  Python1  Python2
A               67       89       92
B               89       67       87
C               26       37       68
D               90       96       79
E               78       56       24
F               76       78       46

In [108]:
df3['Total']=df3['AI for everyone']+df3['Python1']+df3['Python2']
df3

AI for everyone  Python1  Python2  Total
A               67       89       92    248
B               89       67       87    243
C               26       37       68    131
D               90       96       79    265
E               78       56       24    158
F               76       78       46    200

In [116]:
df3["Result"]=df3['Total']>200 
df3

AI for everyone  Python1  Python2  Total  Result
A               67       89       92    248    True
B               89       67       87    243    True
C               26       37       68    131   False
D               90       96       79    265    True
E               78       56       24    158   False
F               76       78       46    200   False

In [117]:
df3[True]="Pass"

In [119]:
del df3[True]

In [120]:
df3

AI for everyone  Python1  Python2  Total  Result
A               67       89       92    248    True
B               89       67       87    243    True
C               26       37       68    131   False
D               90       96       79    265    True
E               78       56       24    158   False
F               76       78       46    200   False

In [161]:
df3["Status"]=["Pass" if a>=33 and p1>=33 and p2>=33 else "Fail" for a,p1,p2 in zip(df3['AI for everyone'],df3['Python1'],df3['Python2']) ]


In [162]:
df3

AI for everyone  Python1  Python2  Total Status  Percenatge
A               67       89       92    248   Pass   82.666667
B               89       67       87    243   Pass   81.000000
C               26       37       68    131   Fail   43.666667
D               90       96       79    265   Pass   88.333333
E               78       56       24    158   Fail   52.666667
F               76       78       46    200   Pass   66.666667

In [164]:
df3["Status2"]=["Pass" if a>=60 and p1>=60 and p2>=60 else "Fail" for a,p1,p2 in zip(df3["AI for everyone"],df3["Python1"],df3["Python2"])]
df3

AI for everyone  Python1  Python2  Total Status  Percenatge Status2
A               67       89       92    248   Pass   82.666667    Pass
B               89       67       87    243   Pass   81.000000    Pass
C               26       37       68    131   Fail   43.666667    Fail
D               90       96       79    265   Pass   88.333333    Pass
E               78       56       24    158   Fail   52.666667    Fail
F               76       78       46    200   Pass   66.666667    Fail

In [145]:
df3["Percenatge"]=(df3["Total"]/300)*100 
df3

AI for everyone  Python1  Python2  Total Status  Percenatge
A               67       89       92    248   Pass   82.666667
B               89       67       87    243   Pass   81.000000
C               26       37       68    131   Fail   43.666667
D               90       96       79    265   Pass   88.333333
E               78       56       24    158   Fail   52.666667
F               76       78       46    200   Pass   66.666667

In [135]:
numbers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
evenArr=[]
oddArr=[]
for num in numbers:
    if num%2==0:
        evenArr.append(num)
    else:
        oddArr.append(num)
print("Even numbers>>>",evenArr)
print("Odd numbers>>>",oddArr)

Even numbers>>> [2, 4, 6, 8, 10, 12, 14]
Odd numbers>>> [1, 3, 5, 7, 9, 11, 13, 15]


In [5]:
df3['status1']=np.where(((df3['AI for everyone']<50) & (df3['Python1']<50) & (df3['Python2']<50)),"Fail","Pass")

NameError: name 'np' is not defined

### Zip operation

In [153]:
a=list(range(5))
b=list(range(6,11))

In [154]:
a

[0, 1, 2, 3, 4]

In [155]:
b


[6, 7, 8, 9, 10]

In [156]:
c=zip(a,b)

In [157]:
for i in c:
    print(i)

(0, 6)
(1, 7)
(2, 8)
(3, 9)
(4, 10)


In [167]:
df3.head()            #head return 5 first rows by default

AI for everyone  Python1  Python2  Total Status  Percenatge Status2
A               67       89       92    248   Pass   82.666667    Pass
B               89       67       87    243   Pass   81.000000    Pass
C               26       37       68    131   Fail   43.666667    Fail
D               90       96       79    265   Pass   88.333333    Pass
E               78       56       24    158   Fail   52.666667    Fail

In [168]:
df3.head(3) 

AI for everyone  Python1  Python2  Total Status  Percenatge Status2
A               67       89       92    248   Pass   82.666667    Pass
B               89       67       87    243   Pass   81.000000    Pass
C               26       37       68    131   Fail   43.666667    Fail

In [170]:
df3.tail()

AI for everyone  Python1  Python2  Total Status  Percenatge Status2
B               89       67       87    243   Pass   81.000000    Pass
C               26       37       68    131   Fail   43.666667    Fail
D               90       96       79    265   Pass   88.333333    Pass
E               78       56       24    158   Fail   52.666667    Fail
F               76       78       46    200   Pass   66.666667    Fail

In [171]:
df3.tail(2)

AI for everyone  Python1  Python2  Total Status  Percenatge Status2
E               78       56       24    158   Fail   52.666667    Fail
F               76       78       46    200   Pass   66.666667    Fail

In [172]:
df3.loc['C']          #Retrieving a particular row

AI for everyone         26
Python1                 37
Python2                 68
Total                  131
Status                Fail
Percenatge         43.6667
Status2               Fail
Name: C, dtype: object

In [173]:
df3.loc['A':'C']       #slicing

AI for everyone  Python1  Python2  Total Status  Percenatge Status2
A               67       89       92    248   Pass   82.666667    Pass
B               89       67       87    243   Pass   81.000000    Pass
C               26       37       68    131   Fail   43.666667    Fail

In [175]:
df3.iloc[3]

AI for everyone         90
Python1                 96
Python2                 79
Total                  265
Status                Pass
Percenatge         88.3333
Status2               Pass
Name: D, dtype: object

In [176]:
df3.loc['C':'E']   #it include last value

AI for everyone  Python1  Python2  Total Status  Percenatge Status2
C               26       37       68    131   Fail   43.666667    Fail
D               90       96       79    265   Pass   88.333333    Pass
E               78       56       24    158   Fail   52.666667    Fail

In [179]:
df3.iloc[0:3]   #it does not include last value

AI for everyone  Python1  Python2  Total Status  Percenatge Status2
A               67       89       92    248   Pass   82.666667    Pass
B               89       67       87    243   Pass   81.000000    Pass
C               26       37       68    131   Fail   43.666667    Fail

In [180]:
df3.iloc[3:5]

AI for everyone  Python1  Python2  Total Status  Percenatge Status2
D               90       96       79    265   Pass   88.333333    Pass
E               78       56       24    158   Fail   52.666667    Fail

In [182]:
df3.loc['E':'B':-1]

AI for everyone  Python1  Python2  Total Status  Percenatge Status2
E               78       56       24    158   Fail   52.666667    Fail
D               90       96       79    265   Pass   88.333333    Pass
C               26       37       68    131   Fail   43.666667    Fail
B               89       67       87    243   Pass   81.000000    Pass

In [183]:
df3.iloc[::-1]

AI for everyone  Python1  Python2  Total Status  Percenatge Status2
F               76       78       46    200   Pass   66.666667    Fail
E               78       56       24    158   Fail   52.666667    Fail
D               90       96       79    265   Pass   88.333333    Pass
C               26       37       68    131   Fail   43.666667    Fail
B               89       67       87    243   Pass   81.000000    Pass
A               67       89       92    248   Pass   82.666667    Pass

In [184]:
df3.loc['C']['Python2']

68

In [188]:
df3.loc['G']=[1,2,3,4,5,6,7]            #Adding  a row
df3

AI for everyone  Python1  Python2  Total Status  Percenatge Status2
A               67       89       92    248   Pass   82.666667    Pass
B               89       67       87    243   Pass   81.000000    Pass
C               26       37       68    131   Fail   43.666667    Fail
D               90       96       79    265   Pass   88.333333    Pass
E               78       56       24    158   Fail   52.666667    Fail
F               76       78       46    200   Pass   66.666667    Fail
G                1        2        3      4      5    6.000000       7