In [1]:
import numpy as np

### Creating array using arange

In [2]:
a=np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_list=list(np.arange(20))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

### randn function

In [6]:
data=np.random.randn(2,3)
data

array([[-0.40159786, -0.80422038,  1.02110529],
       [ 0.25020755, -1.67882467, -0.73512682]])

In [7]:
data*10

array([[ -4.01597855,  -8.04220385,  10.21105287],
       [  2.50207552, -16.78824665,  -7.35126816]])

In [8]:
data+data

array([[-0.80319571, -1.60844077,  2.04221057],
       [ 0.5004151 , -3.35764933, -1.47025363]])

In [9]:
data.shape

(2, 3)

In [10]:
data.ndim

2

In [11]:
data.dtype

dtype('float64')

### Creating an array by giving list

In [13]:
data2=[1.3,4.7,4,8,8.7]
arr1=np.array(data2)

In [14]:
arr1

array([1.3, 4.7, 4. , 8. , 8.7])

In [15]:
data3=[[1,2,3],[4,5,6]]
arr2=np.array(data3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

### np.zeros , np.ones , np.empty functions

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
zero=np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
one=np.ones((2,2))

In [22]:
one

array([[1., 1.],
       [1., 1.]])

In [23]:
empty=np.empty(2)
empty

array([1.14453755e-311, 0.00000000e+000])

In [24]:
empty=np.empty((2,3,2))

In [25]:
empty

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

### dtype

In [27]:
b=np.array([1,2,3],dtype=np.int32)

In [28]:
b

array([1, 2, 3])

In [29]:
c=np.array([214,42,2],dtype=np.float64)

In [30]:
c

array([214.,  42.,   2.])

In [31]:
c.dtype

dtype('float64')

In [32]:
d=np.array([324,7,45,6],dtype=np.int32)
d.dtype

dtype('int32')

In [33]:
floatarrc=d.astype(np.float64)
floatarrc

array([324.,   7.,  45.,   6.])

In [34]:
floatarrc.dtype

dtype('float64')

### string conversion to float

In [36]:
numeric_strings=np.array([23.4,56,3,4.64],dtype=np.string_)
numeric_strings.dtype

dtype('S4')

In [40]:
numeric=numeric_strings.astype(float)
numeric.dtype

dtype('float64')

In [41]:
e=np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
calibres=np.array([1,2,3,5,6],dtype=np.float32)
calibres

array([1., 2., 3., 5., 6.], dtype=float32)

### Another method of typecasting

In [44]:
f=e.astype(calibres.dtype)
f.dtype

dtype('float32')

### Arithmetoc with NumPy arrays

In [47]:
g=np.array([[1,2,3],[4,5,6]],dtype=np.int32)
g

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
g+g

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [49]:
g*g

array([[ 1,  4,  9],
       [16, 25, 36]])

In [50]:
g-g

array([[0, 0, 0],
       [0, 0, 0]])

In [51]:
g/g

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
g**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [53]:
g>g

array([[False, False, False],
       [False, False, False]])

In [54]:
h=np.array([[4,7,3],[2,9,6]],dtype=np.int32)

In [55]:
g>h

array([[False, False, False],
       [ True, False, False]])

In [56]:
h

array([[4, 7, 3],
       [2, 9, 6]])

### Basic slicing and indexing

In [2]:
import numpy as np

In [4]:
i=np.arange(10)
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr_slice=i[4:7]
arr_slice

array([4, 5, 6])

In [6]:
arr_slice[2]=345
arr_slice

array([  4,   5, 345])

In [7]:
i

array([  0,   1,   2,   3,   4,   5, 345,   7,   8,   9])

In [8]:
i[:]=1
i

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [3]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr2d[2]

array([7, 8, 9])

In [5]:
arr2d[1][2]

6

In [6]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,0,0]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 0, 0]]])

In [7]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr3d[0]=1

In [10]:
arr3d

array([[[1, 1, 1],
        [1, 1, 1]],

       [[7, 8, 9],
        [0, 0, 0]]])

In [11]:
arr3d[1,0]=3
arr3d

array([[[1, 1, 1],
        [1, 1, 1]],

       [[3, 3, 3],
        [0, 0, 0]]])

In [12]:
arr3d[1,0,1]=89
arr3d

array([[[ 1,  1,  1],
        [ 1,  1,  1]],

       [[ 3, 89,  3],
        [ 0,  0,  0]]])

## Indexing with slicing

In [5]:
arrr2d = np.array([[1,2,3],[4,5,6]])
arrr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arrr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [7]:
arrr2d[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [8]:
#slicing with indexing

In [9]:
arrr2d[1,1:]

array([5, 6])

In [10]:
arrr2d[:,:1]

array([[1],
       [4]])

### Assigning to slice expression

In [11]:
arrr2d[:1,1:]=0

In [12]:
arrr2d

array([[1, 0, 0],
       [4, 5, 6]])

In [13]:
arrr2d

array([[1, 0, 0],
       [4, 5, 6]])

# Boolean indexing

In [15]:
import numpy as np

In [17]:
names=np.array(['Bob','Saad','Joe','John','Bob','Henry','John'])
names

array(['Bob', 'Saad', 'Joe', 'John', 'Bob', 'Henry', 'John'], dtype='<U5')

In [18]:
names=='Bob'

array([ True, False, False, False,  True, False, False])

In [51]:
data=np.random.randn(7,4)

In [52]:
data

array([[ 0.75642349, -1.01487773,  0.13728458,  0.28068866],
       [-0.05320777, -1.3896354 , -0.09874119,  0.30678106],
       [ 1.44003064,  0.72771282,  0.91515341, -0.49198952],
       [-0.32402043, -0.65714373,  0.67607136, -0.87094258],
       [-2.76041439, -0.30958168, -0.10651972, -1.07032608],
       [-1.22688648,  1.08785298, -0.00989031, -0.48495187],
       [ 0.43139035,  0.77641842,  0.49717266,  1.42528205]])

In [53]:
data[names=='Bob']

array([[ 0.75642349, -1.01487773,  0.13728458,  0.28068866],
       [-2.76041439, -0.30958168, -0.10651972, -1.07032608]])

In [54]:
data>0

array([[ True, False,  True,  True],
       [False, False, False,  True],
       [ True,  True,  True, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False,  True, False, False],
       [ True,  True,  True,  True]])

In [55]:
data[data>1]

array([1.44003064, 1.08785298, 1.42528205])

In [56]:
data[names=='Bob',2:]

array([[ 0.13728458,  0.28068866],
       [-0.10651972, -1.07032608]])

In [57]:
data[names=='Bob']

array([[ 0.75642349, -1.01487773,  0.13728458,  0.28068866],
       [-2.76041439, -0.30958168, -0.10651972, -1.07032608]])

In [58]:
data[names!='Bob']

array([[-0.05320777, -1.3896354 , -0.09874119,  0.30678106],
       [ 1.44003064,  0.72771282,  0.91515341, -0.49198952],
       [-0.32402043, -0.65714373,  0.67607136, -0.87094258],
       [-1.22688648,  1.08785298, -0.00989031, -0.48495187],
       [ 0.43139035,  0.77641842,  0.49717266,  1.42528205]])

In [59]:
data[~(names=='Bob')]

array([[-0.05320777, -1.3896354 , -0.09874119,  0.30678106],
       [ 1.44003064,  0.72771282,  0.91515341, -0.49198952],
       [-0.32402043, -0.65714373,  0.67607136, -0.87094258],
       [-1.22688648,  1.08785298, -0.00989031, -0.48495187],
       [ 0.43139035,  0.77641842,  0.49717266,  1.42528205]])

In [60]:
data[(names == 'Bob') | (names == 'Saad')]

array([[ 0.75642349, -1.01487773,  0.13728458,  0.28068866],
       [-0.05320777, -1.3896354 , -0.09874119,  0.30678106],
       [-2.76041439, -0.30958168, -0.10651972, -1.07032608]])

In [61]:
data[(names == 'Bob') | (names == 'Saad')]

array([[ 0.75642349, -1.01487773,  0.13728458,  0.28068866],
       [-0.05320777, -1.3896354 , -0.09874119,  0.30678106],
       [-2.76041439, -0.30958168, -0.10651972, -1.07032608]])

In [62]:
mask = (names == 'Bob') | (names == 'Saad')
mask

array([ True,  True, False, False,  True, False, False])

In [63]:
data[mask]

array([[ 0.75642349, -1.01487773,  0.13728458,  0.28068866],
       [-0.05320777, -1.3896354 , -0.09874119,  0.30678106],
       [-2.76041439, -0.30958168, -0.10651972, -1.07032608]])

In [64]:
data[data<0] = 0

In [65]:
data

array([[0.75642349, 0.        , 0.13728458, 0.28068866],
       [0.        , 0.        , 0.        , 0.30678106],
       [1.44003064, 0.72771282, 0.91515341, 0.        ],
       [0.        , 0.        , 0.67607136, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.08785298, 0.        , 0.        ],
       [0.43139035, 0.77641842, 0.49717266, 1.42528205]])

In [66]:
data<0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [67]:
data>0

array([[ True, False,  True,  True],
       [False, False, False,  True],
       [ True,  True,  True, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False,  True, False, False],
       [ True,  True,  True,  True]])

In [68]:
data==0

array([[False,  True, False, False],
       [ True,  True,  True, False],
       [False, False, False,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [False, False, False, False]])

In [69]:
data

array([[0.75642349, 0.        , 0.13728458, 0.28068866],
       [0.        , 0.        , 0.        , 0.30678106],
       [1.44003064, 0.72771282, 0.91515341, 0.        ],
       [0.        , 0.        , 0.67607136, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.08785298, 0.        , 0.        ],
       [0.43139035, 0.77641842, 0.49717266, 1.42528205]])

# Fancy indexing

In [2]:
import numpy as np

In [5]:
arra=np.empty((7,3))
arra

array([[6.46707192e-312, 6.27463370e-322, 0.00000000e+000],
       [0.00000000e+000, 6.23053953e-307, 5.30276956e+180],
       [3.31033942e-033, 2.99645216e-066, 5.06557762e-086],
       [3.35609973e-143, 6.01433264e+175, 6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180, 2.36082375e+184],
       [2.81962637e+179, 7.91308478e+165, 2.19183657e-076],
       [5.18964374e-144, 1.50008929e+248, 2.59305228e-306]])

In [6]:
for i in range(7):
    arra[i]=i
arra

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.]])

In [8]:
arra[[0,4,6,1]]       #selecting multiple indices

array([[0., 0., 0.],
       [4., 4., 4.],
       [6., 6., 6.],
       [1., 1., 1.]])

In [9]:
arra[5]               #selecting single index

array([5., 5., 5.])

In [10]:
arra[[2,4,6,2],[1,0,2,1]]

array([2., 4., 6., 2.])

In [11]:
arra[[-6,-3,-2]]

array([[1., 1., 1.],
       [4., 4., 4.],
       [5., 5., 5.]])

In [12]:
arra

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.]])

In [13]:
arra1=np.arange(36).reshape((6,6))
arra1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [15]:
arra1[[1,4,5,2],[1,2,3,4]]

array([ 7, 26, 33, 16])

In [18]:
arra1[[5,4,1,2]][[3,2,1,0]]

array([[12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [24]:
arra2=np.arange(60).reshape((6,2,5))
arra2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [29]:
arra2[3,1,4]

39

In [30]:
arra2[3][1][4]

39

# Transpose of a matrix

In [19]:
arra.T

array([[0., 1., 2., 3., 4., 5., 6.],
       [0., 1., 2., 3., 4., 5., 6.],
       [0., 1., 2., 3., 4., 5., 6.]])

In [20]:
arra1.T

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [21]:
arra1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [22]:
arra1.transpose()

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [31]:
arra3=arra1.copy()

In [32]:
arra3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [33]:
arra1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [36]:
np.dot(arra3.T,arra3)

array([[1980, 2070, 2160, 2250, 2340, 2430],
       [2070, 2166, 2262, 2358, 2454, 2550],
       [2160, 2262, 2364, 2466, 2568, 2670],
       [2250, 2358, 2466, 2574, 2682, 2790],
       [2340, 2454, 2568, 2682, 2796, 2910],
       [2430, 2550, 2670, 2790, 2910, 3030]])

In [38]:
arra3=np.arange(40).reshape((2,4,5))
arra3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [43]:
arra3.transpose((1,0,2))

array([[[ 0,  1,  2,  3,  4],
        [20, 21, 22, 23, 24]],

       [[ 5,  6,  7,  8,  9],
        [25, 26, 27, 28, 29]],

       [[10, 11, 12, 13, 14],
        [30, 31, 32, 33, 34]],

       [[15, 16, 17, 18, 19],
        [35, 36, 37, 38, 39]]])

In [47]:
arra4=np.arange(24).reshape((2,2,6))
arra4

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [49]:
arra4.swapaxes(2,1)

array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11]],

       [[12, 18],
        [13, 19],
        [14, 20],
        [15, 21],
        [16, 22],
        [17, 23]]])

In [50]:
arra4

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [51]:
arra4.swapaxes(1,2)

array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11]],

       [[12, 18],
        [13, 19],
        [14, 20],
        [15, 21],
        [16, 22],
        [17, 23]]])

# defining a set

In [52]:
a=[1,4,2,4,1,5,6,8,3,7,8]
a

[1, 4, 2, 4, 1, 5, 6, 8, 3, 7, 8]

In [54]:
sett=set(a)
sett

{1, 2, 3, 4, 5, 6, 7, 8}

# Concatenation

In [57]:
ar1=np.array([[1,2,3],[4,5,6]])
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
ar2=np.array([[7,8,9],[10,11,12]])
ar2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [60]:
np.concatenate([ar1,ar2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
np.concatenate([ar1,ar2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
np.concatenate([ar1,ar2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# Stack

In [63]:
np.stack([ar1,ar2])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [64]:
np.vstack([ar1,ar2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
np.hstack([ar1,ar2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [66]:
ar3=np.arange(36).reshape((6,6))
ar3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [67]:
np.split(ar3,3)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [68]:
np.split(ar3,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [70]:
np.vsplit(ar3,3)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [71]:
np.hsplit(ar3,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [72]:
ar3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

# Universal functions : Fast element wise array functions

### unary ufunc

In [74]:
x=[1,4,3,5,2]
x

[1, 4, 3, 5, 2]

In [75]:
np.sqrt(x)

array([1.        , 2.        , 1.73205081, 2.23606798, 1.41421356])

In [110]:
ext=np.array([-2,3,4,-3.4])
ext

array([-2. ,  3. ,  4. , -3.4])

In [111]:
np.sqrt(ext)

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 1.73205081, 2.        ,        nan])

In [76]:
np.exp(x)           #compute e to the power x

array([  2.71828183,  54.59815003,  20.08553692, 148.4131591 ,
         7.3890561 ])

In [77]:
y=np.array([1,4.5,3,6.7])
y

array([1. , 4.5, 3. , 6.7])

In [79]:
np.fabs(y)

array([1. , 4.5, 3. , 6.7])

In [80]:
np.abs(y)

array([1. , 4.5, 3. , 6.7])

In [81]:
np.square(y)

array([ 1.  , 20.25,  9.  , 44.89])

In [82]:
np.square(x)

array([ 1, 16,  9, 25,  4], dtype=int32)

In [83]:
z=np.array([1.2,-6.7,-4,3,5])
z

array([ 1.2, -6.7, -4. ,  3. ,  5. ])

In [84]:
np.sign(z)

array([ 1., -1., -1.,  1.,  1.])

In [85]:
np.ceil(z)

array([ 2., -6., -4.,  3.,  5.])

In [86]:
np.floor(z)

array([ 1., -7., -4.,  3.,  5.])

In [87]:
np.rint(z)

array([ 1., -7., -4.,  3.,  5.])

In [88]:
z

array([ 1.2, -6.7, -4. ,  3. ,  5. ])

In [89]:
np.modf(z)

(array([ 0.2, -0.7, -0. ,  0. ,  0. ]), array([ 1., -6., -4.,  3.,  5.]))

In [104]:
remainder , whole_part = np.modf(z)

In [105]:
remainder

array([ 0.2, -0.7, -0. ,  0. ,  0. ])

In [106]:
whole_part

array([ 1., -6., -4.,  3.,  5.])

In [90]:
np.isnan(z)

array([False, False, False, False, False])

In [93]:
stri=np.array(['A','B','C',3,2,'$'])
stri

array(['A', 'B', 'C', '3', '2', '$'], dtype='<U1')

In [95]:
a=np.random.randn(8)

In [96]:
a

array([-1.54520705, -0.33672475, -1.84414968,  0.9311975 , -1.35160654,
       -0.5168377 ,  0.38572095,  1.23706896])

In [98]:
b=np.random.randn(8)

In [99]:
b

array([-0.38178574, -0.90582993,  0.14192133, -0.24625157,  0.02873386,
        2.03123891,  0.57865315,  1.29172761])

In [100]:
np.maximum(a,b)

array([-0.38178574, -0.33672475,  0.14192133,  0.9311975 ,  0.02873386,
        2.03123891,  0.57865315,  1.29172761])

In [101]:
c=np.random.rand(5)
c

array([0.66968058, 0.79422839, 0.21669421, 0.3584714 , 0.04365467])

In [102]:
d=np.random.randn(3)
d

array([0.11822786, 0.80981626, 0.44521277])

In [103]:
np.maximum(c,d)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

# Binary universal functions

In [112]:
x1=np.array([1,3,6,3,213])
x1

array([  1,   3,   6,   3, 213])

In [115]:
x2=np.array([12,34,125,23,1])
x2

array([ 12,  34, 125,  23,   1])

In [116]:
np.add(x1,x2)

array([ 13,  37, 131,  26, 214])

In [117]:
np.subtract(x1,x2)

array([ -11,  -31, -119,  -20,  212])

In [118]:
np.subtract(x2,x1)

array([  11,   31,  119,   20, -212])

In [119]:
np.divide(x1,x2)

array([8.33333333e-02, 8.82352941e-02, 4.80000000e-02, 1.30434783e-01,
       2.13000000e+02])

In [121]:
np.floor_divide(x1,x2)          #floor_divide truncate the decimal part

array([  0,   0,   0,   0, 213], dtype=int32)

In [3]:
x5=np.array([7,5,8])
x6=np.array([2,2,2])
np.floor_divide(x5,x6)

array([3, 2, 4], dtype=int32)

In [120]:
np.multiply(x1,x2)

array([ 12, 102, 750,  69, 213])

In [122]:
x3=np.array([2,3,2])
x4=np.array([2,4,3])
np.power(x3,x4)

array([ 4, 81,  8], dtype=int32)

In [5]:
x7=np.array([2,14,2,6])
x8=np.array([4,6,9,10])
np.maximum(x7,x8)

array([ 4, 14,  9, 10])

In [6]:
np.minimum(x7,x8)

array([2, 6, 2, 6])

In [7]:
np.fmax(x7,x8)         #fmax and fmin ignores NaN

array([ 4, 14,  9, 10])

In [8]:
np.fmin(x7,x8)

array([2, 6, 2, 6])

In [9]:
x9=np.array([-4,5,-2,3,2,-12])
x10=np.array([3,5,-4,5,6,12])
np.copysign(x9,x10)            #Copy sign of values in second argument to values in first argument

array([ 4.,  5., -2.,  3.,  2., 12.])

In [10]:
np.greater(x9,x10)

array([False, False,  True, False, False, False])

In [11]:
np.greater_equal(x9,x10)

array([False,  True,  True, False, False, False])

In [12]:
np.less(x9,x10)

array([ True, False, False,  True,  True,  True])

In [13]:
np.less_equal(x9,x10)

array([ True,  True, False,  True,  True,  True])

In [14]:
np.equal(x9,x10)

array([False,  True, False, False, False, False])

In [15]:
np.not_equal(x9,x10)

array([ True, False,  True,  True,  True,  True])

In [17]:
x11=np.array([[1,0.2,3,0.4],[0.123,2.1,0,5.6]])
x11

array([[1.   , 0.2  , 3.   , 0.4  ],
       [0.123, 2.1  , 0.   , 5.6  ]])

In [19]:
x11<1

array([[False,  True, False,  True],
       [ True, False,  True, False]])

In [20]:
np.where(x11<1 , 1 , 0)

array([[0, 1, 0, 1],
       [1, 0, 1, 0]])

In [21]:
f=np.random.randn(25)

In [22]:
f

array([-0.78136671,  0.18041165,  1.36462592,  0.55251213, -1.6718474 ,
       -1.66177993,  0.8892041 ,  0.66139707,  1.83190842,  0.2336704 ,
        0.11800187,  0.08814988,  0.025945  , -0.28970102,  0.19069039,
       -0.28285817,  0.73362031,  2.5263014 , -1.58822871,  0.10034552,
        0.94472426,  0.56398535, -1.05540182, -0.99425936,  0.2304427 ])

In [38]:
g=np.arange(16).reshape((4,4))
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
np.mean(f)

0.1164197294833774

In [40]:
g.mean(axis=0)

array([6., 7., 8., 9.])

In [41]:
g.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

In [24]:
f.mean()

0.1164197294833774

In [25]:
np.sum(f)

2.910493237084435

In [26]:
f.sum()

2.910493237084435

In [32]:
f.sum(axis=0)

2.910493237084435

In [42]:
g.sum(axis=1)

array([ 6, 22, 38, 54])

In [43]:
g.sum(axis=0)

array([24, 28, 32, 36])

In [44]:
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
f.std()

1.014073743968065

In [27]:
np.std(f)

1.014073743968065

In [45]:
g.std(axis=0)

array([4.47213595, 4.47213595, 4.47213595, 4.47213595])

In [46]:
g.std(axis=1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399])

In [47]:
g.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54]], dtype=int32)

In [48]:
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
g.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]], dtype=int32)

In [50]:
g.cumprod(axis=0)

array([[   0,    1,    2,    3],
       [   0,    5,   12,   21],
       [   0,   45,  120,  231],
       [   0,  585, 1680, 3465]], dtype=int32)

In [52]:
g.cumprod(axis=1)

array([[    0,     0,     0,     0],
       [    4,    20,   120,   840],
       [    8,    72,   720,  7920],
       [   12,   156,  2184, 32760]], dtype=int32)

In [53]:
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
g.min()

0

In [55]:
g.max()

15

In [56]:
g.var()

21.25

In [60]:
h=np.array([[2,465,1,645],[12,756,34,6]])
h

array([[  2, 465,   1, 645],
       [ 12, 756,  34,   6]])

In [63]:
h.argmin()

2

In [64]:
h.argmax()

5

In [65]:
#Methods for boolean arrays
i=np.random.randn(20)
i

array([-1.29791782,  0.49457894,  1.66227638,  1.31929684, -0.63224072,
       -0.96860065,  1.98365019,  0.23271598, -0.42813883, -1.5393801 ,
       -0.28653303, -0.5904613 , -1.94662445, -1.25746845, -2.24061994,
        0.46058338, -0.24602782, -0.03069716, -0.97954011,  2.04534886])

In [69]:
(i>0).sum()

7

In [76]:
bool1=np.array([True,True,True])
bool2=np.array([False,False,True,True,False,True])
bool3=np.array([False,False,False])

In [71]:
bool1.any()

True

In [72]:
bool1.all()

True

In [73]:
bool2.any()

True

In [74]:
bool2.all()

False

In [77]:
bool3.any()

False

In [78]:
bool3.all()

False

# Sorting

In [2]:
import numpy as np

In [5]:
n=np.random.randn(5)

In [6]:
n

array([ 1.62626583e+00, -8.51735257e-04, -1.14805155e+00, -1.34074798e+00,
        1.48525372e+00])

In [7]:
n.sort()

In [8]:
n

array([-1.34074798e+00, -1.14805155e+00, -8.51735257e-04,  1.48525372e+00,
        1.62626583e+00])

In [9]:
l=np.random.randn(5,4)

In [10]:
l

array([[-0.73615164,  1.3063659 ,  0.34436882, -0.06866647],
       [ 0.8839041 , -2.42984807, -0.00894814,  0.27465132],
       [-0.04088783, -0.36501507,  0.53636808, -0.96706771],
       [ 1.62245063, -0.78117669, -0.88294842,  0.01870313],
       [-0.17299756,  0.45336876, -0.84303297,  0.95619871]])

In [14]:
l.sort(1)

In [15]:
l

array([[-0.73615164, -0.06866647,  0.34436882,  1.3063659 ],
       [-2.42984807, -0.00894814,  0.27465132,  0.8839041 ],
       [-0.96706771, -0.36501507, -0.04088783,  0.53636808],
       [-0.88294842, -0.78117669,  0.01870313,  1.62245063],
       [-0.84303297, -0.17299756,  0.45336876,  0.95619871]])

In [16]:
l.sort(0)

In [17]:
l

array([[-2.42984807, -0.78117669, -0.04088783,  0.53636808],
       [-0.96706771, -0.36501507,  0.01870313,  0.8839041 ],
       [-0.88294842, -0.17299756,  0.27465132,  0.95619871],
       [-0.84303297, -0.06866647,  0.34436882,  1.3063659 ],
       [-0.73615164, -0.00894814,  0.45336876,  1.62245063]])

In [18]:
l

array([[-2.42984807, -0.78117669, -0.04088783,  0.53636808],
       [-0.96706771, -0.36501507,  0.01870313,  0.8839041 ],
       [-0.88294842, -0.17299756,  0.27465132,  0.95619871],
       [-0.84303297, -0.06866647,  0.34436882,  1.3063659 ],
       [-0.73615164, -0.00894814,  0.45336876,  1.62245063]])

In [20]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))]                # 5% quantile

-1.5854734534995476

# Unique and other set logic

In [21]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [22]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

# Save and Load arrays

In [2]:
arr = [1,2,3,4,5]
np.save('some_array',arr)

In [3]:
np.load('some_array.npy')

array([1, 2, 3, 4, 5])

In [16]:
arr1 = [12,345,75,3]
arr2 = [324,78,234,8]
np.savez('some_array1.npz',a=arr1,b=arr2)

In [17]:
abc = np.load('some_array1.npz')

In [21]:
abc['a']

array([ 12, 345,  75,   3])

In [22]:
abc['b']

array([324,  78, 234,   8])

# Linear algebra

In [2]:
import numpy as np

In [6]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8],[9,10],[11,12]])

In [7]:
x.dot(y)

array([[ 58,  64],
       [139, 154]])

In [8]:
np.dot(x,y)

array([[ 58,  64],
       [139, 154]])

In [15]:
z=np.arange(12)

In [16]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
x@np.ones(3)        #@ called infix operator used for matrix multiplication

array([ 6., 15.])

In [27]:
y@np.zeros(2)

array([0., 0., 0.])

In [25]:
y@np.ones(2)

array([15., 19., 23.])

In [42]:
from numpy.linalg import inv , qr

In [33]:
xx = np.random.randn(3,2)

In [34]:
mat = xx.T.dot(xx)
inv(mat)

array([[0.15123088, 0.3744166 ],
       [0.3744166 , 3.84072155]])

In [36]:
yy=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.diag(yy)

array([1, 5, 9])

In [37]:
yy.dot(yy.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [46]:
yy.det()

AttributeError: 'numpy.ndarray' object has no attribute 'det'

In [47]:
np.trace(yy)

15

AttributeError: 'numpy.ndarray' object has no attribute 'inv'

# Pseudorandom number 

In [2]:
samples = np.random.normal(size=(4,4))
samples

array([[ 0.02909074,  1.56141218,  0.4397192 , -0.09230089],
       [-0.30767688,  0.75816029, -0.42274077,  0.89528035],
       [ 0.05726509, -0.80991726, -0.21177532, -0.02061249],
       [ 0.44743395, -0.17598115,  0.19146788,  0.03089084]])

In [3]:
sample1 = np.random.randn(4,4)

In [5]:
sample1

array([[ 2.39099868, -0.58069755, -1.48821851,  1.72543875],
       [ 1.18016722, -0.00848058, -0.28806917, -0.2329138 ],
       [-0.19787024,  0.60999066, -0.9614637 ,  0.25343613],
       [ 0.37790727,  0.87111468, -0.1025822 , -2.35111223]])

In [12]:
import random

In [13]:
zz=np.random.seed(1234)  #not working

In [19]:
zz1=np.random.RandomState()

In [20]:
zz1.randn(10)

array([ 0.41593717,  0.73030997,  1.20988924,  1.11105138,  1.38319504,
        0.20373409,  0.93539688, -0.0281235 ,  2.10792122, -0.52188326])

In [21]:
zz2 = np.random.permutation(10)

In [22]:
zz2

array([7, 2, 9, 1, 0, 8, 4, 5, 6, 3])

In [32]:
np.random.shuffle(4)

AttributeError: module 'numpy' has no attribute 'RandomState'

# Appendix A

## Numpy dtype hierarchy

In [2]:
np.float64.mro()               #mro is used to see all the parent classes of a specific dtype

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

## Reshaping arrays

In [3]:
xxx = np.arange(12)

In [4]:
xxx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
xxx.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Concatenating and spitting arrays

In [7]:
aarr1 = np.array([[1,2,3],[4,5,6]])
aarr2 = np.array([[7,8,9],[10,11,12]])

In [10]:
np.concatenate([aarr1,aarr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
np.concatenate([aarr1,aarr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### Stack

In [12]:
np.vstack((aarr1,aarr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
np.hstack((aarr1,aarr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## Split

In [15]:
barr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
barr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [19]:
bsplit = np.split(barr,[1,3])

In [20]:
bsplit

[array([[1, 2, 3]]), array([[4, 5, 6],
        [7, 8, 9]]), array([[10, 11, 12],
        [13, 14, 15]])]

In [24]:
hhsplit = np.hsplit(barr,[1,3])
hhsplit

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13]]), array([[ 2,  3],
        [ 5,  6],
        [ 8,  9],
        [11, 12],
        [14, 15]]), array([], shape=(5, 0), dtype=int32)]

In [25]:
vvsplit = np.vsplit(barr, [1,3])

In [26]:
vvsplit

[array([[1, 2, 3]]), array([[4, 5, 6],
        [7, 8, 9]]), array([[10, 11, 12],
        [13, 14, 15]])]

## Stacking helpers i.e r_ and c_

In [27]:
arrrr1=np.array([[234,675,2,657],[54,12,56,3]])
arrrr2=np.array([[3,65,2,6],[24,57,254,5]])
np.r_[arrrr1,arrrr2]

array([[234, 675,   2, 657],
       [ 54,  12,  56,   3],
       [  3,  65,   2,   6],
       [ 24,  57, 254,   5]])

In [28]:
np.c_[arrrr1,arrrr2]

array([[234, 675,   2, 657,   3,  65,   2,   6],
       [ 54,  12,  56,   3,  24,  57, 254,   5]])

## Repeat and tile

In [31]:
ar = np.array([1,2,3])
ar.repeat([5,2,3])

array([1, 1, 1, 1, 1, 2, 2, 3, 3, 3])

In [32]:
arr2d = np.array([[2,2,6],[2,54,2]])
arr2d.repeat(2,axis=0)

array([[ 2,  2,  6],
       [ 2,  2,  6],
       [ 2, 54,  2],
       [ 2, 54,  2]])

In [33]:
arr2d.repeat(2,axis=1)

array([[ 2,  2,  2,  2,  6,  6],
       [ 2,  2, 54, 54,  2,  2]])

In [34]:
arr2d.repeat([3,4],axis=0)  #if we don't write any axis then it is by default 0(rows will increase)

array([[ 2,  2,  6],
       [ 2,  2,  6],
       [ 2,  2,  6],
       [ 2, 54,  2],
       [ 2, 54,  2],
       [ 2, 54,  2],
       [ 2, 54,  2]])

In [35]:
arr2d1 = np.array([[234,67,2],[3,86,2]])
arr2d1

array([[234,  67,   2],
       [  3,  86,   2]])

In [36]:
np.tile(arr2d1 , (2,3))

array([[234,  67,   2, 234,  67,   2, 234,  67,   2],
       [  3,  86,   2,   3,  86,   2,   3,  86,   2],
       [234,  67,   2, 234,  67,   2, 234,  67,   2],
       [  3,  86,   2,   3,  86,   2,   3,  86,   2]])

In [37]:
np.tile(arr2d1 , (5,3))

array([[234,  67,   2, 234,  67,   2, 234,  67,   2],
       [  3,  86,   2,   3,  86,   2,   3,  86,   2],
       [234,  67,   2, 234,  67,   2, 234,  67,   2],
       [  3,  86,   2,   3,  86,   2,   3,  86,   2],
       [234,  67,   2, 234,  67,   2, 234,  67,   2],
       [  3,  86,   2,   3,  86,   2,   3,  86,   2],
       [234,  67,   2, 234,  67,   2, 234,  67,   2],
       [  3,  86,   2,   3,  86,   2,   3,  86,   2],
       [234,  67,   2, 234,  67,   2, 234,  67,   2],
       [  3,  86,   2,   3,  86,   2,   3,  86,   2]])

## Fancy indexing

In [53]:
aa = np.arange(10)*50
aa

array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450])

In [54]:
indexx = [3,7,2]
aa[indexx]

array([150, 350, 100])

#### another method(Take and put)

In [55]:
aa.take(indexx)

array([150, 350, 100])

In [56]:
aa.put(indexx,[43,56,78])

In [57]:
aa

array([  0,  50,  78,  43, 200, 250, 300,  56, 400, 450])

In [58]:
indexx1 = [0,1]
aa.put(indexx1 , 99)

In [59]:
aa

array([ 99,  99,  78,  43, 200, 250, 300,  56, 400, 450])

In [60]:
aaa1 = np.random.randn(4,2)
aaa1

array([[ 0.4665139 ,  0.34449367],
       [-0.24387661,  1.49237209],
       [-0.22228158,  0.4477813 ],
       [-0.51378885, -0.28814436]])

In [64]:
indexx2 = [3,2,0,2]
aaa1.take(indexx2,axis = 0)

array([[-0.51378885, -0.28814436],
       [-0.22228158,  0.4477813 ],
       [ 0.4665139 ,  0.34449367],
       [-0.22228158,  0.4477813 ]])

In [65]:
aaa2 = np.random.randn(2,5)
aaa2

array([[-0.58075452,  1.19803135,  0.59757044,  0.11803876,  0.45519921],
       [-0.48739683, -1.09477881,  0.38096891,  2.07355478, -2.26162788]])

In [67]:
indexx3 = [4,0,1]
aaa2.take(indexx3,axis=1)

array([[ 0.45519921, -0.58075452,  1.19803135],
       [-2.26162788, -0.48739683, -1.09477881]])

## Broadcasting

In [2]:
arra = np.random.randn(4,3)

In [3]:
arra

array([[ 0.62410485, -1.48566115,  0.61509845],
       [ 0.15974115,  0.85754196,  0.30949514],
       [-0.06339027,  1.10468819,  1.32233102],
       [ 0.67195161, -4.06667138, -0.54943153]])

In [4]:
arra.mean(0)

array([ 0.34810183, -0.8975256 ,  0.42437327])

In [5]:
arra.mean(1)

array([-0.08215262,  0.44225942,  0.78787631, -1.3147171 ])

In [15]:
arra1=arra[np.newaxis , :]

In [16]:
np.shape(arra1)

(1, 4, 3)

In [8]:
aarr = np.zeros((4,4))

In [10]:
aarr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
aarr1 = aarr[np.newaxis , :]

In [14]:
np.shape(aarr1)

(1, 4, 4)

In [17]:
arr1d = np.random.normal(size = 3)

In [18]:
arr1d

array([-0.97519576, -1.73122447,  0.01384919])

In [19]:
arr1d[np.newaxis,:]

array([[-0.97519576, -1.73122447,  0.01384919]])

In [20]:
arr1d[:,np.newaxis]

array([[-0.97519576],
       [-1.73122447],
       [ 0.01384919]])

In [25]:
arr1d.mean(0)

-0.8975236808469677

In [26]:
arr1d

array([-0.97519576, -1.73122447,  0.01384919])

In [29]:
arr2d = np.random.randn(4,3)

In [30]:
arr2d

array([[ 0.04766021,  0.49813264, -0.15097292],
       [-0.08588362, -0.73524927,  0.12168272],
       [-1.31657234, -1.36413071, -0.60587163],
       [-0.59950709,  1.40768551, -0.05911741]])

In [32]:
arr2dmean = arr2d.mean(0)

In [34]:
demeaned = arr2d - arr2dmean

In [35]:
demeaned

array([[ 0.53623592,  0.5465231 ,  0.02259689],
       [ 0.40269209, -0.68685882,  0.29525253],
       [-0.82799663, -1.31574025, -0.43230182],
       [-0.11093138,  1.45607597,  0.1144524 ]])

In [36]:
xxx = np.arange(12).reshape(3,4)

In [55]:
yyy = np.arange(3).reshape(3,1)

In [56]:
yyy

array([[0],
       [1],
       [2]])

In [57]:
xxx

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
xxx,yyy = np.broadcast_arrays(xxx,yyy)

In [59]:
xxx

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
yyy

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

## Setting array values by broadcasting

In [64]:
rarrr = np.arange(12).reshape(4,3)

In [65]:
rarrr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [68]:
cols= np.array([88,88,88,88])

In [69]:
rarrr[:] = cols[:,np.newaxis]

In [70]:
rarrr

array([[88, 88, 88],
       [88, 88, 88],
       [88, 88, 88],
       [88, 88, 88]])

In [71]:
rarrr[0:2] = [[12],[34]]

In [72]:
rarrr

array([[12, 12, 12],
       [34, 34, 34],
       [88, 88, 88],
       [88, 88, 88]])

In [73]:
np.add.accumulate(rarrr,axis = 0)

array([[ 12,  12,  12],
       [ 46,  46,  46],
       [134, 134, 134],
       [222, 222, 222]], dtype=int32)

In [74]:
np.add.accumulate(rarrr,axis = 1)

array([[ 12,  24,  36],
       [ 34,  68, 102],
       [ 88, 176, 264],
       [ 88, 176, 264]], dtype=int32)