# Replacing values

In [1]:
import pandas as pd
import numpy as np
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [2]:
#we can use replace producing a new series(unless you pass inplae=True)
#value to be replaced is first argument 
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [21]:
data.replace(-999,'a')

0       1
1       a
2       2
3       a
4   -1000
5       3
dtype: object

In [22]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [6]:
#to use a different replacement for eah value,
# pass a list of substitutes
data.replace([-999,-1000],[100,200])

0      1.0
1    100.0
2      2.0
3    100.0
4    200.0
5      3.0
dtype: float64

In [8]:
data.replace({-999:0 , -1000:1.0})
#by using a dcitioinary:  keys value be the values that you want to change 

0    1.0
1    0.0
2    2.0
3    0.0
4    1.0
5    3.0
dtype: float64

# Renaming axis indexes

In [9]:
data1 = pd.DataFrame(np.arange(12).reshape((3, 4)), 
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data1

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [11]:
transform = lambda x: x[:4].upper()
#like a series , the axis indexes have a map method
data1.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [12]:
#you can assign to index , modifying the dataframe in-place
#no argument for map like  inplae=True that's why we need to explicitly assign it
data1.index= data1.index.map(transform)

In [13]:
data1

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [14]:
#temporary change in data1
#convert indexes into title and columns into upper
data1.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [16]:
data1

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [20]:
#renaming using dictionary
data1.rename(index={'OHIO': 'INDIANA'},
             columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

# Discretization and binning

In [25]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
#intervals from (18-25]-->0(code/index), (25-35]-->1(code/index), (35-60]-->2, (60-100]-->3
#( means not inluded  and ] means inluded
#bins is just a variable
#pandas consider it as interval when we pass it in cut

In [26]:
#first argument me vo values jo check krni hai k kis interval me lie kr rhi hai
#second argument me interval
cats = pd.cut(ages, bins)
cats
#in output 18 is not included and 25 is inluded

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [27]:
ages1 = [18, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins1 = [18, 25, 35, 60, 100]
cats1 = pd.cut(ages1, bins1)
cats1
#first output is nan because 18 is not included in any interval

[NaN, (18.0, 25.0], (18.0, 25.0], (25.0, 35.0], (18.0, 25.0], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [28]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [29]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [30]:
 pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [32]:
pd.cut(ages1, [18, 26, 36, 61, 100], right=False)
#first parameter me jo chek krna hai wo pass krenge 
#seond parameter direct list pass krdi jo phle bins me bnai thi
#third parameter right p open bracket dega
#by default right=True

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [33]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
group_names

['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [34]:
pd.cut(ages, bins, labels=group_names)
#we use labels to inrease readability 
#if we give labels then it will not show intervals nut labels

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [35]:
data2 = np.random.rand(20)

In [36]:
data2

array([0.48035518, 0.8273476 , 0.86887028, 0.42812952, 0.19101325,
       0.37781432, 0.78611708, 0.25164974, 0.46769456, 0.18804887,
       0.68558771, 0.88945212, 0.92895137, 0.73423051, 0.88369079,
       0.43442063, 0.92208441, 0.93535872, 0.1189691 , 0.39048048])

In [37]:
pd.cut(data2, 4, precision=2)
#it will make 4 intervals by its own and truncate the value to 2 decimal points 

[(0.32, 0.53], (0.73, 0.94], (0.73, 0.94], (0.32, 0.53], (0.12, 0.32], ..., (0.32, 0.53], (0.73, 0.94], (0.73, 0.94], (0.12, 0.32], (0.32, 0.53]]
Length: 20
Categories (4, interval[float64]): [(0.12, 0.32] < (0.32, 0.53] < (0.53, 0.73] < (0.73, 0.94]]

# Detecting and Filtering Outliers

In [38]:
data3 = pd.DataFrame(np.random.randn(1000, 4))
data3

0         1         2         3
0   -0.955732 -0.875102 -0.160575  0.167093
1   -1.386181 -1.554323 -1.349901  0.023385
2    0.752397  0.474968  0.148688 -0.891737
3    1.495894  0.353201  1.760480 -0.344529
4    0.860953 -0.053801 -0.578338  0.177015
5   -0.149977 -0.694958  0.586192 -1.388697
6    0.162219  1.563962  3.357780  0.276644
7   -1.037532  1.675200  1.218115 -0.346713
8   -0.148154 -1.135405  0.398264 -0.491781
9    1.596465  1.201035  0.665432 -0.725973
10   1.151368  0.159433 -0.078108 -0.015676
11  -0.387746 -0.937977 -3.284907  0.816447
12  -2.140925 -0.847357  0.965849  0.572881
13  -1.788524  1.417064 -0.677720 -1.178316
14   1.584852 -1.125791  0.674958 -0.151968
15   0.320793 -0.599465  1.711190  0.488542
16   2.227406 -0.284169  1.074971  1.868013
17  -1.194225 -0.306549 -1.121984 -1.211768
18   0.390700 -0.522588 -0.105697 -0.718380
19   0.786408 -0.116955 -0.051107  0.911230
20  -0.316896 -0.559136  0.851751  0.140069
21   0.461721  0.320709 -0.476497  1.241300
22  -0.503231 -0.121515  1.548085 -1.002990
23  -0.754916 -0.605183  0.494839 -0.662548
24  -0.418379  0.922253 -1.397086 -0.310630
25   0.929717 -0.375829 -0.577324  0.305431
26   0.761928 -0.247451  0.781312 -1.233600
27  -0.722531 -0.119351  0.130743  0.504688
28  -0.110285  1.198833  1.412149 -1.293963
29  -0.801419 -1.258644  0.394053 -0.478049
..        ...       ...       ...       ...
970  1.425796 -1.087627 -1.398732  0.412176
971  2.497814  0.997627 -1.651951  1.463225
972  0.838634 -0.863714  0.498100 -1.283639
973  2.098189  0.898069 -0.826794 -0.495973
974  0.405130  2.543227 -0.158470 -0.639293
975 -0.503936 -2.213294  0.580606 -0.162171
976  0.979146 -1.296117 -0.044172 -0.359051
977 -0.718188 -0.627631 -0.123744  1.084437
978  0.589174  0.267745  0.056178 -0.218874
979  0.324013 -1.248905  0.855972  0.709518
980  1.010912 -0.525247 -0.449634 -0.381357
981 -1.861507  0.639348  0.504249  1.052745
982  0.277015  0.025845 -0.183549 -1.815618
983 -0.887579 -1.564663  0.458959  0.598807
984  1.094594  0.878558 -0.162177  0.139627
985 -0.834501  0.256129  0.752730 -1.818235
986 -0.638736 -0.474784  0.740047  0.246095
987 -1.547257  0.660112 -0.657657 -0.665022
988 -0.072960 -0.530571 -0.305098  0.495688
989 -1.462904 -0.971508  0.390362  0.720830
990  0.657459 -0.136987  1.400448 -0.549580
991 -0.551270 -1.427544 -0.363153 -1.471130
992  0.326583  0.495904  0.174048 -0.326772
993  1.226773  0.448944  0.675463  0.499259
994  0.298452 -0.948536 -0.168243  1.312407
995 -0.098920 -0.046649 -0.082680  0.196144
996 -0.273480 -0.696058  0.949507 -0.080073
997  0.314815 -0.397263 -0.037006 -1.056425
998 -1.567279  0.868540  0.378803  1.156410
999 -0.289863 -0.073092 -0.518709 -0.343200

[1000 rows x 4 columns]

In [40]:
data3.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.009361    -0.063640     0.038646    -0.046396
std       1.008299     0.993517     0.978700     0.937953
min      -3.092698    -2.736202    -3.284907    -3.000687
25%      -0.688111    -0.777751    -0.608594    -0.662667
50%       0.013878    -0.071422     0.027792    -0.031022
75%       0.693800     0.613899     0.706510     0.599327
max       3.221230     2.924931     3.357780     2.585634

In [41]:
col = data3.head(10)
col

0         1         2         3
0 -0.955732 -0.875102 -0.160575  0.167093
1 -1.386181 -1.554323 -1.349901  0.023385
2  0.752397  0.474968  0.148688 -0.891737
3  1.495894  0.353201  1.760480 -0.344529
4  0.860953 -0.053801 -0.578338  0.177015
5 -0.149977 -0.694958  0.586192 -1.388697
6  0.162219  1.563962  3.357780  0.276644
7 -1.037532  1.675200  1.218115 -0.346713
8 -0.148154 -1.135405  0.398264 -0.491781
9  1.596465  1.201035  0.665432 -0.725973

In [42]:
np.abs(col)

0         1         2         3
0  0.955732  0.875102  0.160575  0.167093
1  1.386181  1.554323  1.349901  0.023385
2  0.752397  0.474968  0.148688  0.891737
3  1.495894  0.353201  1.760480  0.344529
4  0.860953  0.053801  0.578338  0.177015
5  0.149977  0.694958  0.586192  1.388697
6  0.162219  1.563962  3.357780  0.276644
7  1.037532  1.675200  1.218115  0.346713
8  0.148154  1.135405  0.398264  0.491781
9  1.596465  1.201035  0.665432  0.725973

In [43]:
np.abs(col) >=1

0      1      2      3
0  False  False  False  False
1   True   True   True  False
2  False  False  False  False
3   True  False   True  False
4  False  False  False  False
5  False  False  False   True
6  False   True   True  False
7   True   True   True  False
8  False   True  False  False
9   True   True  False  False

In [44]:
col[np.abs(col) >=1]

0         1         2         3
0       NaN       NaN       NaN       NaN
1 -1.386181 -1.554323 -1.349901       NaN
2       NaN       NaN       NaN       NaN
3  1.495894       NaN  1.760480       NaN
4       NaN       NaN       NaN       NaN
5       NaN       NaN       NaN -1.388697
6       NaN  1.563962  3.357780       NaN
7 -1.037532  1.675200  1.218115       NaN
8       NaN -1.135405       NaN       NaN
9  1.596465  1.201035       NaN       NaN

In [45]:
np.abs(col[np.abs(col)>=1])

0         1         2         3
0       NaN       NaN       NaN       NaN
1  1.386181  1.554323  1.349901       NaN
2       NaN       NaN       NaN       NaN
3  1.495894       NaN  1.760480       NaN
4       NaN       NaN       NaN       NaN
5       NaN       NaN       NaN  1.388697
6       NaN  1.563962  3.357780       NaN
7  1.037532  1.675200  1.218115       NaN
8       NaN  1.135405       NaN       NaN
9  1.596465  1.201035       NaN       NaN

In [46]:
col[col>=1]

0         1         2   3
0       NaN       NaN       NaN NaN
1       NaN       NaN       NaN NaN
2       NaN       NaN       NaN NaN
3  1.495894       NaN  1.760480 NaN
4       NaN       NaN       NaN NaN
5       NaN       NaN       NaN NaN
6       NaN  1.563962  3.357780 NaN
7       NaN  1.675200  1.218115 NaN
8       NaN       NaN       NaN NaN
9  1.596465  1.201035       NaN NaN

In [47]:
col[(np.abs(col)>=1).any(1)]   #1 for column axis

0         1         2         3
1 -1.386181 -1.554323 -1.349901  0.023385
3  1.495894  0.353201  1.760480 -0.344529
5 -0.149977 -0.694958  0.586192 -1.388697
6  0.162219  1.563962  3.357780  0.276644
7 -1.037532  1.675200  1.218115 -0.346713
8 -0.148154 -1.135405  0.398264 -0.491781
9  1.596465  1.201035  0.665432 -0.725973

In [51]:
col[(np.abs(col)>=1).all(1)]

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [48]:
np.sign(col)   #it tells whether value is +ve or -ve

0    1    2    3
0 -1.0 -1.0 -1.0  1.0
1 -1.0 -1.0 -1.0  1.0
2  1.0  1.0  1.0 -1.0
3  1.0  1.0  1.0 -1.0
4  1.0 -1.0 -1.0  1.0
5 -1.0 -1.0  1.0 -1.0
6  1.0  1.0  1.0  1.0
7 -1.0  1.0  1.0 -1.0
8 -1.0 -1.0  1.0 -1.0
9  1.0  1.0  1.0 -1.0

# Permutation and Random Sampling

In [56]:
#permutation return int array of range that we passed
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [57]:
sampler = np.random.permutation(5)
sampler
#every time we execute it, it will give differnet answer 

array([1, 3, 4, 0, 2])

In [58]:
df.take(sampler)   #it reads sampler as an index

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11

In [62]:
df.sample(n=3)

0   1   2   3
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3

In [63]:
df.sample(n=3)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11

In [64]:
df.sample(n=3)       #very large data is present and out of whih 3 will be shown

0   1   2   3
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3

In [65]:
help(df.sample)

Help on method sample in module pandas.core.generic:

sample(n=None, frac=None, replace=False, weights=None, random_state=None, axis=None) method of pandas.core.frame.DataFrame instance
    Return a random sample of items from an axis of object.
    
    You can use `random_state` for reproducibility.
    
    Parameters
    ----------
    n : int, optional
        Number of items from axis to return. Cannot be used with `frac`.
        Default = 1 if `frac` = None.
    frac : float, optional
        Fraction of axis items to return. Cannot be used with `n`.
    replace : bool, default False
        Sample with or without replacement.
    weights : str or ndarray-like, optional
        Default 'None' results in equal probability weighting.
        If passed a Series, will align with target object on index. Index
        values in weights not found in sampled object will be ignored and
        index values in sampled object not in weights will be assigned
        weights of zero.
      

In [66]:
?df.sample()  #similar to help

Object `df.sample()  #similar to help` not found.


# Computing Indicator/Dummy Variables

In [69]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [68]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [70]:
a=[1,2,3]
a.append(4)

In [71]:
a

[1, 2, 3, 4]

In [76]:
#append add only 1 value , it append whole list at 1 index only
b=[1,2,3]
b.append([4,5,6])
b

[1, 2, 3, [4, 5, 6]]

In [74]:
#extend takes iterative objects
a.extend('5')
a     #only strings

[1, 2, 3, 4, '5']

In [77]:
a.extend([6,7,8])

In [78]:
a

[1, 2, 3, 4, '5', 6, 7, 8]

In [81]:
#seed freeze random values so that these random values will not change on every execution
np.random.seed(12345)

In [83]:
values = np.random.rand(10)
values

array([0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371,
       0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535])

# String Object Methods

In [85]:
val = 'a,b, guido'
val.split()  #by default split with space

['a,b,', 'guido']

In [86]:
val.split(',')

['a', 'b', ' guido']

In [99]:
val1= 'Presidential Initiative for Artifiial Intelligene and computing'
val1

'Presidential Initiative for Artifiial Intelligene and computing'

In [107]:
val1=val1.split()
val1

['Presidential',
 'Initiative',
 'for',
 'Artifiial',
 'Intelligene',
 'and',
 'computing']

In [108]:
print(val1[0]+" "+val1[1]+" "+val1[2]+" "+val1[3]+" "+val1[4]+" "+val1[5]+" "+val1[6]+" ")

Presidential Initiative for Artifiial Intelligene and computing 


In [109]:
" ".join(val1)

'Presidential Initiative for Artifiial Intelligene and computing'

In [110]:
'Presidential' in val1

True

In [111]:
val1.index('Presidential')

0

In [112]:
val1.index('for')

2

In [113]:
val1[0].index('d')

5

In [116]:
val1[0][val1[0].index('d')]

'd'

In [118]:
val1[0].find('z')       
#if index is not present it will give -1 if present then 1

-1

In [119]:
val1[0].find('d')

5

# CHAPTER # 8

In [120]:
#now series is multiindexing
import numpy as np
import pandas as pd

In [121]:
#multiindexing in series
data4 = pd.Series(np.random.randn(9),
         index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],  #0 index child is another list's 0 index
                [1, 2, 3, 1, 3, 1, 2, 2, 3]])   #a ka child 1, a ka child 2, a ka child 3 ...
data4    

a  1    1.352917
   2    0.886429
   3   -2.001637
b  1   -0.371843
   3    1.669025
c  1   -0.438570
   2   -0.539741
d  2    0.476985
   3    3.248944
dtype: float64

In [122]:
data4['a']

1    1.352917
2    0.886429
3   -2.001637
dtype: float64

In [124]:
data4['a'][2]

0.8864293405915888

In [125]:
data4['d'][3]

3.248943919430755

In [126]:
data4['c'][2]

-0.5397414455216628

In [128]:
data4['a':'c':2]

a  1    1.352917
   3   -2.001637
b  3    1.669025
c  2   -0.539741
dtype: float64

In [129]:
data4.loc['a':'c':2]

a  1    1.352917
   3   -2.001637
b  3    1.669025
c  2   -0.539741
dtype: float64

In [131]:
data4.loc[['a','b','c']]

a  1    1.352917
   2    0.886429
   3   -2.001637
b  1   -0.371843
   3    1.669025
c  1   -0.438570
   2   -0.539741
dtype: float64

In [132]:
data4.loc[:,[2,1]]

a  1    1.352917
   2    0.886429
b  1   -0.371843
c  1   -0.438570
   2   -0.539741
d  2    0.476985
dtype: float64

In [136]:
data4.loc['a':'b',3]

a  3   -2.001637
b  3    1.669025
dtype: float64

In [137]:
data4.loc[:,3]

a   -2.001637
b    1.669025
d    3.248944
dtype: float64

In [138]:
data4.unstack()
#unstack convert multi index into dataframe

1         2         3
a  1.352917  0.886429 -2.001637
b -0.371843       NaN  1.669025
c -0.438570 -0.539741       NaN
d       NaN  0.476985  3.248944

In [139]:
data4.unstack().stack()
#stack onvert dataframe into series

a  1    1.352917
   2    0.886429
   3   -2.001637
b  1   -0.371843
   3    1.669025
c  1   -0.438570
   2   -0.539741
d  2    0.476985
   3    3.248944
dtype: float64

In [141]:
#multiindeing in dataframe
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),       
                     index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                     columns=[['Pakistan', 'Pakistan', 'India'],
                     ['Karachi', 'Lahore', 'Delhi']])
frame

Pakistan        India
     Karachi Lahore Delhi
a 1        0      1     2
  2        3      4     5
b 1        6      7     8
  2        9     10    11

In [142]:
frame['Pakistan']['Lahore']['b'][2]

10

In [155]:
frame['Pakistan'].loc['b',2]

Karachi     9
Lahore     10
Name: (b, 2), dtype: int32

In [156]:
frame.columns.names=['Country','City']
frame

Country Pakistan        India
City     Karachi Lahore Delhi
a 1            0      1     2
  2            3      4     5
b 1            6      7     8
  2            9     10    11

In [158]:
frame.index.names=['key1','key2']

In [159]:
frame

Country   Pakistan        India
City       Karachi Lahore Delhi
key1 key2                      
a    1           0      1     2
     2           3      4     5
b    1           6      7     8
     2           9     10    11